### ISSUE TITLE
HeroCarousel

### ISSUE THREAD

**Issue by Vsoftcrackers** [Vsoftcrackers/RajalakshmiCrackers#11]
Ask UI team for images and i have given you link https://www.bulletcrackers.in/ check this link do hero carousel section like this but before starting kindly plan the image and make it responsive in all devices

**Comment by sankarsantosh99** [comment]
Building component for Hero carousal ,images needed for the slides.

**Comment by sankarsantosh99** [comment]
Working on building the carousel

**Comment by sankarsantosh99** [comment]
completed the Hero carousel and pushed the code with test images
