### ISSUE TITLE
Footer Section

### ISSUE THREAD

**Issue by Vsoftcrackers** [Vsoftcrackers/RajalakshmiCrackers#21]
Kindly do this footer and modify this footer section into stylish footer section![Image](https://github.com/user-attachments/assets/d2c01a81-5481-479f-8f8d-03660ed2380a)

**Comment by sankarsantosh99** [comment]
Building footer component.

**Comment by sankarsantosh99** [comment]
Building footer component and aligning

**Comment by sankarsantosh99** [comment]
built footer component

**Comment by sankarsantosh99** [comment]
Finished homepage 
footer
