### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by Vsoftcrackers** [Vsoftcrackers/RajalakshmiCrackers#28]
Refer stylish contact page and make a contact page for the rajalakshmi crackers website with emailjs service with proper service https://www.kuruvicrackers.com/contact   ----- refer the link and finish the page

**Comment by SornaLatha17** [comment]
today i have started the contact page

**Comment by SornaLatha17** [comment]
some error in contact page to rectify the code

**Comment by SornaLatha17** [comment]
task completed and also learn the css
