### ISSUE TITLE
Admin panel all products page

### ISSUE THREAD

**Issue by Vsoftcrackers** [Vsoftcrackers/RajalakshmiCrackers#30]
create a  all products page in react and css only dont need to do any functions in it https://www.figma.com/design/nqvt453pIkzsY4zCvIZyXq/Admin-Dashboard-(-E-commerce-)design-(Community)?node-id=1-3239

**Comment by sankarsantosh99** [comment]
Started building Admin all products page

**Comment by sankarsantosh99** [comment]
Working on all products page in admin panel

**Comment by sankarsantosh99** [comment]
working on all products page and pushed to git

**Comment by sankarsantosh99** [comment]
uploaded all products page.

**Comment by sankarsantosh99** [comment]
alterations in products page

**Comment by sankarsantosh99** [comment]
completed all products page
